// Writes supabase/seed.sql from src/data/products.ts, so the database starts
// with exactly what the site shows before Supabase is connected.
// Run: npm run db:seed-sql
import { writeFileSync } from "node:fs";
import { DEFAULT_SETTINGS, PRODUCTS } from "../src/data/products.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const rows = PRODUCTS.map(
  (p) =>
    `  (${[
      q(p.slug),
      q(p.name),
      q(p.tagline),
      q(p.description),
      q(p.color),
      q(p.ink),
      p.price.toFixed(2),
      p.barsPerBox,
      p.weightGrams,
      `${q(JSON.stringify(p.nutrition))}::jsonb`,
      q(p.ingredients),
      p.sortOrder,
    ].join(", ")})`,
);

const sql = `-- Generated by scripts/generate-seed.ts from src/data/products.ts. Don't edit by hand.
-- PLACEHOLDER prices and nutrition until the owner sends the real ones.

insert into public.products
  (slug, name, tagline, description, color, ink, price, bars_per_box, weight_grams, nutrition, ingredients, sort_order)
values
${rows.join(",\n")}
on conflict (slug) do nothing;

insert into public.settings (id, currency, delivery_fee, free_delivery_over)
values (1, ${q(DEFAULT_SETTINGS.currency)}, ${DEFAULT_SETTINGS.deliveryFee.toFixed(2)}, ${
  DEFAULT_SETTINGS.freeDeliveryOver === null ? "null" : DEFAULT_SETTINGS.freeDeliveryOver.toFixed(2)
})
on conflict (id) do nothing;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`supabase/seed.sql written with ${PRODUCTS.length} products`);
