-- Generated by scripts/generate-seed.ts from src/data/products.ts. Don't edit by hand.
-- PLACEHOLDER prices and nutrition until the owner sends the real ones.

insert into public.products
  (slug, name, tagline, description, color, ink, price, bars_per_box, weight_grams, nutrition, ingredients, sort_order)
values
  ('almond', 'Almond', 'Natural & nutty', 'Roasted almonds folded into a soft, chewy base with a toasted-nut finish. The everyday bar: steady energy that keeps you going between meetings, workouts and everything in between.', '#CEA67D', 'espresso', 30.00, 12, 60, '{"protein":15,"calories":180,"carbs":21,"sugar":3,"fat":8,"fibre":6}'::jsonb, 'Milk protein blend, almonds, almond butter, soluble fibre, cocoa butter, sea salt.', 1),
  ('strawberry', 'Strawberry', 'Fruity & vibrant', 'Real strawberry pieces in a creamy, bright bar that tastes like dessert and works like fuel. For the afternoon slump, the post-run cool-down, the moment you want something sweet that''s still on plan.', '#A04150', 'cream', 30.00, 12, 60, '{"protein":20,"calories":210,"carbs":22,"sugar":4,"fat":7,"fibre":6}'::jsonb, 'Milk protein blend, freeze-dried strawberries, white chocolate coating, soluble fibre, natural flavouring.', 2),
  ('dark-chocolate', 'Dark Chocolate', 'Rich & indulgent', 'Deep cocoa, a fudgy middle and dark chocolate chunks. The one you''ll reach for when you''ve earned it, and the one that makes an early start feel less early.', '#556A78', 'cream', 30.00, 12, 60, '{"protein":21,"calories":230,"carbs":20,"sugar":2,"fat":9,"fibre":7}'::jsonb, 'Milk protein blend, dark chocolate (70% cocoa), cocoa powder, soluble fibre, cocoa butter, sea salt.', 3),
  ('coconut-matcha', 'Coconut Matcha', 'Fresh & balanced', 'Ceremonial-grade matcha meets toasted coconut for a clean, lightly sweet bar with a gentle lift. Calm focus in your bag, wherever the day takes you.', '#9EA488', 'espresso', 30.00, 12, 60, '{"protein":19,"calories":215,"carbs":20,"sugar":3,"fat":9,"fibre":6}'::jsonb, 'Milk protein blend, desiccated coconut, matcha green tea powder, soluble fibre, coconut oil.', 4)
on conflict (slug) do nothing;

insert into public.settings (id, currency, delivery_fee, free_delivery_over)
values (1, 'USD', 3.00, 60.00)
on conflict (id) do nothing;
